on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output: ["ttf-nerd-zip", "ttf-zip", "web-zip"]
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: experimental-features = nix-command flakes

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          nix build .#${{ matrix.output }} -L
          cp -vL ./result ./iosevka-${{ matrix.output }}.zip

      - uses: ncipollo/release-action@v1
        name: Release
        with:
          omitBody: true
          omitName: true
          allowUpdates: true
          artifacts: iosevka-${{ matrix.output }}.zip
